services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development  # Change to 'production' for production builds
    ports:
      - "5000:5000"
    volumes:
      - .:/usr/src/app  # Mount the current directory to enable live reloading in development
    environment:
      NODE_ENV: development  # Set environment variables if needed
      DATABASE_URL: ${DATABASE_URL}  # Reference the DATABASE_URL from .env

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}  # Reference MySQL root password from .env
      MYSQL_DATABASE: ${MYSQL_DATABASE}  # Reference database name from .env
      MYSQL_USER: user                   # Create a new user if needed
      MYSQL_PASSWORD: password  
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
